site_name: 半落天外的笔记
site_url: https://Nuyoah718.github.io/MyMkDocsSite/

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.top
  icon:
    repo: fontawesome/brands/github   # 右上角 GitHub 图标
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换夜间模式

# 仓库信息（显示在右上角）
repo_url: https://github.com/Nuyoah718/MyMkDocsSite
repo_name: Nuyoah718/MyMkDocsSite

nav:
  - 首页: index.md
  - ES源码学习:
      - 简介: ES源码学习/README.md
      - 写入: ES源码学习/写入.md
      - 插件开发: ES源码学习/Fastbulk设计文档.md
  - 工具学习:
      - Mkdocs部署: 工具学习/mkdocs部署.md
