site_name: 半落天外的笔记
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换夜间模式
nav:
  - 首页: index.md
  - ES源码学习 :
      - 简介: ES源码学习/README.md
      - 笔记: ES源码学习/Notes.md
